// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go.uber.org/zap"
	"interchange/config"
	"interchange/internal/command"
	command2 "interchange/internal/command/handler"
	"interchange/internal/cron"
	"interchange/internal/middleware"
	"interchange/internal/router"
)

import (
	_ "interchange/cmd/docs"
)

// Injectors from wire.go:

// wireApp init application.
func wireApp(configuration *config.Configuration, zapLogger *zap.Logger) (*App, func(), error) {
	recovery := middleware.NewRecovery(zapLogger, configuration)
	cors := middleware.NewCors()
	middlewareLogger := middleware.NewLogger(zapLogger, configuration)
	response := middleware.NewResponse(zapLogger, configuration)
	engine := router.NewRouter(configuration, recovery, cors, middlewareLogger, response)
	server := newHttpServer(configuration, engine)
	cronCron := cron.NewCron(zapLogger)
	app := newApp(configuration, zapLogger, server, cronCron)
	return app, func() {
	}, nil
}

// wireCommand init application.
func wireCommand(configuration *config.Configuration, zapLogger *zap.Logger) (*command.Command, func(), error) {
	exampleHandler := command2.NewExampleHandler(zapLogger)
	commandCommand := command.NewCommand(exampleHandler)
	return commandCommand, func() {
	}, nil
}
